### ISSUE TITLE
Game fails to launch after 1.1.0.8 update

### ISSUE THREAD

**Issue by drakon64** [rankynbass/XIVLauncher.Core#25]
After upgrading to XIVLauncher-RB 1.1.0.8, the game fails to launch. The terminal shows the following:

```
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
libEGL warning: egl: failed to create dri2 screen
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
Using WINEDLLOVERRIDES="msquic=,mscoree=n,b;d3d11,dxgi=n,b;winmm=n,b"
x86_64-linux-gnu-capsule-capture-libs: warning: Dependencies of libnvidia-pkcs11.so.555.58.02 not found, ignoring: Missing dependencies: Could not find "libcrypto.so.1.1" in LD_LIBRARY_PATH "/lib64:/lib32:/steamrt/amd64/lib/x86_64-linux-gnu:/steamrt/amd64/lib:/steamrt/amd64/usr/lib/x86_64-linux-gnu:/steamrt/amd64/usr/lib:/steamrt/i386/lib/i386-linux-gnu:/steamrt/i386/lib:/steamrt/i386/usr/lib/i386-linux-gnu:/steamrt/i386/usr/lib:/run/opengl-driver/lib:/run/opengl-driver-32/lib:/nix/store/qvi7lcfbvsgz87d7x93xzgssh5zj4is1-icu4c-73.2/lib:/nix/store/i6kf25g918pjk18f7v6d5cp3zmmflzav-SDL2-2.30.2/lib:/nix/store/5r4c3m7vy5ircrqvb18ww97rpf0hf6xp-libsecret-0.21.4/lib:/nix/store/8mg16qnlbdxlwcxva9p228fqmbc70i4p-glib-2.80.2/lib:/nix/store/5w8r7swhhs7vc0l1zcdq0iq6a98nczhz-gnutls-3.8.5/lib", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
pressure-vessel-wrap[6487]: W: Found more than one possible libdrm data directory from provider
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
wine: using kernel write watches, use_kernel_writewatch 1.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
fsync: up and running.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
wine: using kernel write watches, use_kernel_writewatch 1.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
wine: using kernel write watches, use_kernel_writewatch 1.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
wine: using kernel write watches, use_kernel_writewatch 1.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
wine: using kernel write watches, use_kernel_writewatch 1.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
wine: using kernel write watches, use_kernel_writewatch 1.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
wine: using kernel write watches, use_kernel_writewatch 1.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
wine: using kernel write watches, use_kernel_writewatch 1.
[15:30:10 INF] --------------------------------------------------------------------------------
[15:30:10 INF] Dalamud.Injector, (c) 2023 XIVLauncher Contributors
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
wine: using kernel write watches, use_kernel_writewatch 1.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
wine: using kernel write watches, use_kernel_writewatch 1.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
wine: using kernel write watches, use_kernel_writewatch 1.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
wine: using kernel write watches, use_kernel_writewatch 1.
[15:30:10 ERR] [GameStart] Uncaught error during initialization, trying to kill process
Dalamud.Injector.GameStart+GameStartException: Game exited prematurely.
   at Dalamud.Injector.GameStart.LaunchGame(String workingDir, String exePath, String arguments, Boolean dontFixAcl, Action`1 beforeResume, Boolean waitForGameWindow) in C:\goatsoft\companysecrets\injector\GameStart.cs:line 138
[15:30:10 ERR] Operation failed.
Dalamud.Injector.GameStart+GameStartException: Game exited prematurely.
   at Dalamud.Injector.GameStart.LaunchGame(String workingDir, String exePath, String arguments, Boolean dontFixAcl, Action`1 beforeResume, Boolean waitForGameWindow) in C:\goatsoft\companysecrets\injector\GameStart.cs:line 138
   at Dalamud.Injector.EntryPoint.ProcessLaunchCommand(List`1 args, DalamudStartInfo dalamudStartInfo) in C:\goatsoft\companysecrets\injector\EntryPoint.cs:line 826
   at Dalamud.Injector.EntryPoint.Main(Int32 argc, IntPtr argvPtr) in C:\goatsoft\companysecrets\injector\EntryPoint.cs:line 111
```

I cannot reproduce this with XIVLauncher-RB 1.1.0.6.

OS: NixOS 24.05
Kernel: 6.10.2 with CachyOS patches
Graphics: NVIDIA proprietary
Wine: UMU Proton
Dalamud load method: DLL Injection

I do have DLSSTweaks enabled.

**Comment by drakon64** [comment]
This also seems to be reproducible on Nobara https://discord.com/channels/581875019861328007/850387047927250944/1269281503964041318

**Comment by rankynbass** [comment]
I've updated to 1.1.0.9. I've added a button to update the steam runtime in the wine tab. Use that and then clear the prefix, and then try again. And don't use GE-Proton9-11, XIV-Proton9-11 or (maybe) Proton-Experimental. There appears to be something in recent bleeding edge proton that can break the prefix.
