### ISSUE TITLE
Unable to download DXVK in launcher

### ISSUE THREAD

**Issue by foophoof** [rankynbass/XIVLauncher.Core#30]
At some point recently I seem to have stopped being able to download DXVK through the launcher, I now get an error when doing so.

It's possible this has always been broken for me, since I'm using Proton and I only now realised that the DXVK version set in the launcher doesn't matter when using Proton, and I see the code to show the error was only recently added, but regardless figured I'd mention it.

Here's a log of me trying to download all the versions listed in the dropdown:

<details><summary><code>launcher.log</code></summary>

```
2024-11-13 15:59:31.915 +00:00 [INF] ========================================================
2024-11-13 15:59:31.920 +00:00 [INF] Starting a session(v1.1.1.2 - c87a594)
2024-11-13 15:59:32.129 +00:00 [INF] DLSS: nvngx.dll found at /usr/lib64/nvidia/wine
2024-11-13 15:59:32.211 +00:00 [ERR] Failed to initialize Steam entry 39210 - FFXIV Retail
2024-11-13 15:59:32.257 +00:00 [INF] Successfully initialized Steam entry 312060 - FFXIV Free Trial
2024-11-13 15:59:32.258 +00:00 [INF] [DUPDATE] Starting... (forceProxy: false)
2024-11-13 15:59:32.623 +00:00 [INF] [DUPDATE] Using release version (10.0.0.15)
2024-11-13 15:59:32.777 +00:00 [INF] [DUPDATE] Now starting for .NET Runtime 8.0.0
2024-11-13 15:59:34.507 +00:00 [INF] TROUBLESHXLTING:eyJXaGVuIjoiMjAyNC0xMS0xM1QxNTo1OTozNC40OTcyMTA3KzAwOjAwIiwiSXNBdXRvTG9naW4iOmZhbHNlLCJJc1VpZENhY2hlIjpmYWxzZSwiRGFsYW11ZEVuYWJsZWQiOnRydWUsIkRhbGFtdWRMb2FkTWV0aG9kIjowLCJEYWxhbXVkSW5qZWN0aW9uRGVsYXkiOjAuMCwiU3RlYW1JbnRlZ3JhdGlvbiI6ZmFsc2UsIkVuY3J5cHRBcmd1bWVudHMiOnRydWUsIkxhdW5jaGVyVmVyc2lvbiI6IjEuMS4xLjIiLCJMYXVuY2hlckhhc2giOiJjODdhNTk0IiwiT2ZmaWNpYWwiOmZhbHNlLCJEcGlBd2FyZW5lc3MiOjEsIlBsYXRmb3JtIjoyLCJPYnNlcnZlZEdhbWVWZXJzaW9uIjoiMjAyNC4xMS4wNi4wMDAwLjAwMDAiLCJPYnNlcnZlZEV4MVZlcnNpb24iOiIyMDI0LjExLjAxLjAwMDAuMDAwMCIsIk9ic2VydmVkRXgyVmVyc2lvbiI6IjIwMjQuMTEuMDIuMDAwMC4wMDAwIiwiT2JzZXJ2ZWRFeDNWZXJzaW9uIjoiMjAyNC4xMS4wNi4wMDAwLjAwMDAiLCJPYnNlcnZlZEV4NFZlcnNpb24iOiIyMDI0LjExLjA2LjAwMDAuMDAwMCIsIk9ic2VydmVkRXg1VmVyc2lvbiI6IjIwMjQuMTEuMDYuMDAwMC4wMDAwIiwiQmNrTWF0Y2giOnRydWUsIkluZGV4SW50ZWdyaXR5Ijo1fQ==
2024-11-13 15:59:34.656 +00:00 [INF] [DUPDATE] All set for 2024.08.21.0000.0000 with 10.0.0.15(8.0.0, 289)
2024-11-13 15:59:41.449 +00:00 [ERR] Could not download https://github.com/doitsujin/dxvk/releases/download/v2.5/dxvk-2.5.tar.gz
System.ArgumentException: Empty or null string passed as url.
   at XIVLauncher.Common.Unix.Compatibility.CompatibilityTools.DownloadTool(DirectoryInfo installDirectory, String downloadUrl) in C:/goatsoft/xl/XIVLauncher.Common.Unix/Compatibility/CompatibilityTools.cs:line 167
   at XIVLauncher.Common.Unix.Compatibility.CompatibilityTools.DownloadDxvk() in C:/goatsoft/xl/XIVLauncher.Common.Unix/Compatibility/CompatibilityTools.cs:line 154
   at XIVLauncher.Core.Components.SettingsPage.Tabs.SettingsTabDxvk.<Draw>b__13_0() in C:/goatsoft/xl/XIVLauncher.Core/Components/SettingsPage/Tabs/SettingsTabDxvk.cs:line 132
2024-11-13 16:01:16.943 +00:00 [ERR] Could not download https://gitlab.com/Ph42oN/dxvk-gplasync/-/raw/main/releases/dxvk-gplasync-v2.4.1-1.tar.gz
System.ArgumentException: Empty or null string passed as url.
   at XIVLauncher.Common.Unix.Compatibility.CompatibilityTools.DownloadTool(DirectoryInfo installDirectory, String downloadUrl) in C:/goatsoft/xl/XIVLauncher.Common.Unix/Compatibility/CompatibilityTools.cs:line 167
   at XIVLauncher.Common.Unix.Compatibility.CompatibilityTools.DownloadDxvk() in C:/goatsoft/xl/XIVLauncher.Common.Unix/Compatibility/CompatibilityTools.cs:line 154
   at XIVLauncher.Core.Components.SettingsPage.Tabs.SettingsTabDxvk.<Draw>b__13_0() in C:/goatsoft/xl/XIVLauncher.Core/Components/SettingsPage/Tabs/SettingsTabDxvk.cs:line 132
2024-11-13 16:01:20.867 +00:00 [ERR] Could not download https://github.com/doitsujin/dxvk/releases/download/v2.2/dxvk-2.2.tar.gz
System.ArgumentException: Empty or null string passed as url.
   at XIVLauncher.Common.Unix.Compatibility.CompatibilityTools.DownloadTool(DirectoryInfo installDirectory, String downloadUrl) in C:/goatsoft/xl/XIVLauncher.Common.Unix/Compatibility/CompatibilityTools.cs:line 167
   at XIVLauncher.Common.Unix.Compatibility.CompatibilityTools.DownloadDxvk() in C:/goatsoft/xl/XIVLauncher.Common.Unix/Compatibility/CompatibilityTools.cs:line 154
   at XIVLauncher.Core.Components.SettingsPage.Tabs.SettingsTabDxvk.<Draw>b__13_0() in C:/goatsoft/xl/XIVLauncher.Core/Components/SettingsPage/Tabs/SettingsTabDxvk.cs:line 132
2024-11-13 16:01:25.694 +00:00 [ERR] Could not download https://github.com/Sporif/dxvk-async/releases/download/1.10.3/dxvk-async-1.10.3.tar.gz
System.ArgumentException: Empty or null string passed as url.
   at XIVLauncher.Common.Unix.Compatibility.CompatibilityTools.DownloadTool(DirectoryInfo installDirectory, String downloadUrl) in C:/goatsoft/xl/XIVLauncher.Common.Unix/Compatibility/CompatibilityTools.cs:line 167
   at XIVLauncher.Common.Unix.Compatibility.CompatibilityTools.DownloadDxvk() in C:/goatsoft/xl/XIVLauncher.Common.Unix/Compatibility/CompatibilityTools.cs:line 154
   at XIVLauncher.Core.Components.SettingsPage.Tabs.SettingsTabDxvk.<Draw>b__13_0() in C:/goatsoft/xl/XIVLauncher.Core/Components/SettingsPage/Tabs/SettingsTabDxvk.cs:line 132
```

</details>

I tried to switch to Wine as well just in case there was some issue with having Proton selected, but I got the same errors.

**Comment by foophoof** [comment]
I switched back to Wine today for other reasons and now the DXVK download works fine, so maybe it was related to having Proton selected and I just messed something up when attempting to switch away last time.

**Comment by yaomtc** [comment]
Experienced this too. Had a Proton version selected and DXVK would not download. Switched to XIV-NTSYNC and I could download DXVK again.
